---
name: Checks
on: [push]
jobs: 
  test_lint:
    name: Test and List
    runs-on: ubunbtu-20.04 #Operating system to run on
    steps:
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
        username: 
